application: swagclip
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.py
  
error_handlers:
  - file: static/errors/default_error.html
